# Feature Creation (Feature Engineering)

Feature creation is the process of generating new input variables (features) from existing data to improve the performance of a machine learning model.

Instead of using raw data directly, we transform or combine columns to create more meaningful information.

### Why Feature Creation is Important?
- Helps models understand patterns better
- Improves accuracy and performance
- Converts raw data into useful signals

> Feature creation helps turn raw data into meaningful features that make machine learning models more effective.

---

## 1. Extracting Date Features (Customer Transactions Dataset)

### Load datset
datset link: https://www.kaggle.com/datasets/fares279/customers-transactions?utm_source=chatgpt.com

In [1]:
import pandas as pd
df = pd.read_csv("Customer_Transactions.csv")

### Reading first five row

In [2]:
df.head()

,customer_id,age,gender,country,annual_income,spending_score,num_purchases,avg_purchase_value,membership_years,website_visits_per_month,cart_abandon_rate,churned,feedback_text,last_purchase_date
0,1,37,Male,Germany,85886,14,18,41.20,6,20,0.95,0,Very satisfied with my purchase.,2025-06-22
1,2,40,Male,India,41041,4,10,31.73,4,29,0.21,0,Good quality and value for money.,2025-10-17
2,3,69,Female,Australia,143869,59,39,65.96,12,26,0.08,0,Excellent customer service.,2025-07-01
3,4,30,Male,UK,87261,45,34,51.87,12,7,0.61,0,Good quality and value for money.,2025-08-17
4,5,69,Female,UK,110678,40,38,59.64,13,16,0.49,0,Excellent customer service.,2025-06-21

###  creating Feature

In [3]:
df["last_purchase_date"] = pd.to_datetime(df["last_purchase_date"])
df["Year"] = df["last_purchase_date"].dt.year
df["Month"] = df["last_purchase_date"].dt.month
df["Day"] = df["last_purchase_date"].dt.day

### again read dataset after creating feature

In [4]:
df.head()

,customer_id,age,gender,country,annual_income,spending_score,num_purchases,avg_purchase_value,membership_years,website_visits_per_month,cart_abandon_rate,churned,feedback_text,last_purchase_date,Year,Month,Day
0,1,37,Male,Germany,85886,14,18,41.20,6,20,0.95,0,Very satisfied with my purchase.,2025-06-22,2025,6,22
1,2,40,Male,India,41041,4,10,31.73,4,29,0.21,0,Good quality and value for money.,2025-10-17,2025,10,17
2,3,69,Female,Australia,143869,59,39,65.96,12,26,0.08,0,Excellent customer service.,2025-07-01,2025,7,1
3,4,30,Male,UK,87261,45,34,51.87,12,7,0.61,0,Good quality and value for money.,2025-08-17,2025,8,17
4,5,69,Female,UK,110678,40,38,59.64,13,16,0.49,0,Excellent customer service.,2025-06-21,2025,6,21

In this example, we use the **Customer Transactions Dataset** from Kaggle.

The dataset contains a column `last_purchase_date`, which we convert into a datetime format and extract useful components like year, month, and day.

This helps the model capture time-based patterns in customer behavior.

### Why this is useful?
- Identifies seasonal trends (month)
- Captures yearly patterns
- Helps analyze customer activity over time

---

## 2. Profit Calculation & Date Feature Extraction

### Load datset
dataset link: https://www.kaggle.com/datasets/faresashraf1001/supermarket-sales

In [5]:
import pandas as pd
df = pd.read_csv("SuperMarket Analysis.csv")

### Read first five row

In [6]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

### Creating profit feature in dataset

In [7]:
df["Profit"] = df["Sales"] - df["cogs"]

### Creating year feature from the date
**Note:** in dataset date is not in datetime format so first convert it into datetime format and then creating feature.

In [8]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df["Year"] = df["Date"].dt.year

### Read dataset after creating feature

In [9]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Profit,Year
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,26.1415,2019
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6,3.8200,2019
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,16.2155,2019
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,23.2880,2019
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3,30.2085,2019

In this example, we use the **Supermarket Sales Dataset** from Kaggle.

We create a new feature called `Profit` using sales and cost data. We also convert the `Date` column into datetime format and extract the year.

### Why this is useful?
- Profit helps measure business performance
- Year helps identify trends over time
- Improves model understanding with meaningful features

---

## 3 Creating Age from Birth Date

### Load datset
dataset link: https://www.kaggle.com/datasets/mexwell/famous-birthdays

In [10]:
import pandas as pf
df = pd.read_csv("birthdays.csv")

### Read first five row

In [11]:
df.head()

  lastname firstname  articleNum   birthDate  birthMonth  birthDay     zodiac
0  Aaliyah       NaN           0  1979-01-16         1.0      16.0  Capricorn
1    Aaron      Hank          46  1934-02-05         2.0       5.0   Aquarius
2   Abacha      Sani           2  1943-09-20         9.0      20.0      Virgo
3   Abbado   Claudio           9  1933-06-26         6.0      26.0     Cancer
4    Abbas   Mahmoud         306  1935-03-26         3.0      26.0      Aries

### Creating age feature

**Note:**
- Firstly correct the format of birthdate to datetime
- Importing datetime from datetime modile which used to get today's date
- After that applying simple math, convert it into age

In [12]:
from datetime import datetime
df["birthDate"] = pd.to_datetime(df["birthDate"], errors="coerce")
today = datetime.today()
df["Age"] = today.year - df["birthDate"].dt.year

### Read dataset after creating feature

In [13]:
df.head()

,lastname,firstname,articleNum,birthDate,birthMonth,birthDay,zodiac,Age
0,Aaliyah,NaN,0,1979-01-16,1.0,16.0,Capricorn,47.0
1,Aaron,Hank,46,1934-02-05,2.0,5.0,Aquarius,92.0
2,Abacha,Sani,2,1943-09-20,9.0,20.0,Virgo,83.0
3,Abbado,Claudio,9,1933-06-26,6.0,26.0,Cancer,93.0
4,Abbas,Mahmoud,306,1935-03-26,3.0,26.0,Aries,91.0

In this example, we use the **Famous Birthdays Dataset** from Kaggle.

We convert the `birthDate` column into datetime format and create a new feature `Age` using the current year.

### Why this is useful?
- Converts date into a numerical feature (age)
- Makes data more useful for modeling
- Helps analyze age-related patterns